CREATE DATABASE IF NOT EXISTS todo;
USE todo;
CREATE TABLE IF NOT EXISTS zadania (
    id INT AUTO_INCREMENT PRIMARY KEY,
    zadanie VARCHAR(255) NOT NULL,
    czyZrobione TINYINT(1) NOT NULL DEFAULT 0
);